-- Run in the Supabase SQL editor. Safe to re-run: every statement is
-- "if not exists", so existing tables and data are left alone.
--
-- Existing installs only need the last two sections (budgets, last_billed).
-- Until they run, the app keeps working: budgets fall back to the BUDGETS /
-- MONTHLY_BUDGET env vars, and subscription renewals are not auto-logged.

-- ---------------------------------------------------------------------------
-- Base tables (fresh setup)
-- ---------------------------------------------------------------------------

create table if not exists txns (
    id         bigint generated by default as identity primary key,
    date       text not null,            -- YYYY-MM-DD (queried with LIKE 'YYYY-MM-%')
    category   text not null,
    amount     numeric not null,
    note       text not null default '',
    type       text not null default 'expense' check (type in ('expense', 'income')),
    chat_id    bigint not null,
    created_at timestamptz not null default now()
);
create index if not exists txns_chat_created_idx on txns (chat_id, created_at desc);
create index if not exists txns_date_idx on txns (date);

create table if not exists subscriptions (
    id         bigint generated by default as identity primary key,
    name       text not null,
    amount     numeric not null,
    cycle      text not null check (cycle in ('monthly', 'yearly')),
    chat_id    bigint not null,
    active     boolean not null default true,
    created_at timestamptz not null default now()
);

-- Rate limiting for Gemini-backed endpoints and login (lib/ratelimit.py).
create table if not exists api_requests (
    id          bigint generated by default as identity primary key,
    endpoint    text not null,
    client_hash text not null,
    created_at  timestamptz not null default now()
);
create index if not exists api_requests_lookup_idx on api_requests (endpoint, client_hash, created_at);

-- ---------------------------------------------------------------------------
-- Budgets editable from Telegram (/setbudget) and the dashboard.
-- category "_monthly" holds the overall monthly budget; amount 0 = no cap.
-- ---------------------------------------------------------------------------

create table if not exists budgets (
    category   text primary key,
    amount     numeric not null check (amount >= 0),
    updated_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Date of the last renewal the daily cron auto-logged for each subscription,
-- so a renewal is logged once per period even if you delete that entry.
-- ---------------------------------------------------------------------------

alter table subscriptions add column if not exists last_billed date;

-- The app connects with the service role key (SUPABASE_KEY), which bypasses
-- RLS; enabling it keeps the new table closed to the public anon key.
alter table budgets enable row level security;
